### ISSUE TITLE
Support git packs

### ISSUE THREAD

**Issue by Feandil** [kost/dvcs-ripper#6]
When a git repo contains packed resources, rip-git.pl does not download the pack and only tries to download the objects directly, which will fail as such objects do not exist...

I tried to look around to see if it's possible to guess the name of the pack (when you can't list objects/pack) but so far nothing.

Do you think that's doable?

**Comment by kost** [comment]
Hello!

Yes, currently there's no good way to get the packed objects in dvcs-ripper. 

There are two good resources for git structure info;
https://git-scm.com/docs/gitrepository-layout
https://stackoverflow.com/questions/5469978/git-pack-filenames-what-is-the-digest

According to documentation, objects/info/packs should hold information which packs are available, but I did not see it very often (it's not updated or it's not present at all). According to documentation:
This file is to help dumb transports discover what packs are available in this object store. Whenever a pack is added or removed, git update-server-info should be run to keep this file up-to-date if the repository is published for dumb transports. git repack does this by default.

Another good tip is that: <SHA1> is a hash of the sorted object names to make the resulting filename based on the pack content.

That means that if there's not too much objects, we can try combination of each objects (sorted) and guess the name of the packed content. Did not try this, but this is one of my plans to implement it when I have enough time. Patches are welcome if you plan to play with it before :)

**Comment by kost** [comment]
In the meantime, I have updated dvcs-ripper to support objects/info/packs : https://github.com/kost/dvcs-ripper/commit/b885f76dadc283a099d5372f0c5b0fb41005467d

Still, if that file is not present - guessing pack file names is tough process. As I mentioned in previous post, best bet is to get all missing objects (sha1) and trying all combinations of missing objects in order to guess pack name (sha1). Problem here is that we might not know sha1 of all missing objects, so it can be chicken/egg problem sometimes.

Alternative is to brute force sha1 which does not sound feasible.
